version: '3.8'


services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  web:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://username:password@db:5432/flask_db


volumes:
  db_data:
