[project]
name = "flask-postgres-app"
version = "0.1.0"
description = "Basic Flask app with PostgreSQL"
authors = [
    {name = "Developer"}
]
readme = "README.md"
requires-python = "^3.9"
dependencies = [
    "flask (>=3.1.1,<4.0.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
