name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
    contents: read
    packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: flask_db
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U username && break
            sleep 1
          done

      - name: Run tests
        env:
          DATABASE_URL: postgresql://username:password@localhost:5432/flask_db
        run: pytest -q

      - name: Build Docker image
        run: docker build -t workshop-flask .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
      # run: docker push ghcr.io/taskfore/flask-app-devops:latest
        run: docker push ghcr.io/${{ github.repository }}:latest
